[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tamaradratlerr", email = "tdratler@frba.utn.edu.ar" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.4",
    "sqlalchemy>=2.1.3",
]
