"""agregar fecha_de_carga a books

Revision ID: 56939fa23b5e
Revises: a906d5969088
Create Date: 2026-10-08 13:04:42.059445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56939fa23b5e'
down_revision: Union[str, Sequence[str], None] = 'a906d5969088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('fecha_de_carga', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'fecha_de_carga')
    # ### end Alembic commands ###
