CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "username" varchar,
  "created_at" timestamp
);

CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "quotes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_book_id" integer NOT NULL,
  "text" text NOT NULL,
  "page" integer
);

CREATE TABLE "book_authors" (
  "book_id" integer,
  "author_id" integer,
  PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "books" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "original_title" varchar,
  "description" text,
  "published_date" date,
  "page_count" integer,
  "cover_url" text,
  "isbn_13" varchar(13),
  "language" varchar,
  "series_name" varchar,
  "series_number" integer,
  "open_library_id" varchar
);

CREATE TABLE "user_books" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "book_id" integer NOT NULL,
  "status" varchar NOT NULL,
  "rating" decimal(2,1),
  "current_page" integer,
  "review" text,
  "started_at" date,
  "finished_at" date,
  "added_at" date
);

CREATE UNIQUE INDEX ON "user_books" ("user_id", "book_id");

COMMENT ON COLUMN "quotes"."text" IS 'Text';

COMMENT ON COLUMN "books"."description" IS 'Description';

COMMENT ON COLUMN "books"."cover_url" IS 'Cover URL';

COMMENT ON COLUMN "user_books"."review" IS 'Review';

ALTER TABLE "quotes" ADD FOREIGN KEY ("user_book_id") REFERENCES "user_books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_authors" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_books" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_books" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;
